### PR TITLE
FRO-43: Feat - Setting Page Functionality

### PR DESCRIPTION
**Pull request by Michaelajayi150**

### CODE REVIEW

**Review by OkoloJohnbosco — CHANGES_REQUESTED** [review]
@Michaelajayi150 Please resolve this conflict

**Comment by Michaelajayi150** [comment]
@OkoloJohnbosco I have done that.... Everything is fine now

**Comment by shalomtaiwo** [comment]
🫠 Add screenshot / video @Michaelajayi150

**Comment by Michaelajayi150** [comment]
https://user-images.githubusercontent.com/63158015/204160054-e9e2e69a-723a-4b79-bd48-d3e29c8273f9.mp4

This is the video explaining what I did... The Font change only affects the conversation page while the languages change update the user data so that the language is what he/she selected

**Review by shalomtaiwo — APPROVED** [review]
Thanks!

**Pull request merged**
