### PR TITLE
fix:(FRO-17): fixed the page by adding shadows and margins etc

### PR DESCRIPTION
**Pull request by preshpi**

### CODE REVIEW

**Comment by OkoloJohnbosco** [comment]
Post a screenshot of what u did.

**Comment by preshpi** [comment]
https://res.cloudinary.com/dpokiomqq/image/upload/v1669195878/Screen_Shot_2022-11-23_at_10.29.39_AM_thdh58.png

The down part of the page

**Comment by preshpi** [comment]
https://www.awesomescreenshot.com/video/12718374
see mobile

**Review by shalomtaiwo — CHANGES_REQUESTED** [review]
Please do an origin pull and push again

**Comment by preshpi** [comment]
@shalomtaiwo I've done that

**Pull request merged**
