### PR TITLE
Feat/fro2 104/authentication

### PR DESCRIPTION
**Pull request by bimbo-ade**
appropriate changes made to facebook login. Users can now login in with facebook

### CODE REVIEW

**Comment by bimbo-ade** [comment]
thanks money..it works fine

**Comment by OkoloJohnbosco** [comment]
> thanks money..it works fine

Are u sure? @bimbo-ade

**Comment by bimbo-ade** [comment]
maybe you should test it @OkoloJohnbosco

**Comment by OkoloJohnbosco** [comment]
Ok ma'am @bimbo-ade

**Pull request merged**
