### PR TITLE
Feat: Setting Page Functionality

### PR DESCRIPTION
**Pull request by Michaelajayi150**

### CODE REVIEW

**Comment by shalomtaiwo** [comment]
Please wait a while. you'll need to pull and resolve conflicts. Have a build that's being merged

**Comment by Michaelajayi150** [comment]
Has the build been merged now??

**Comment by OkoloJohnbosco** [comment]
> Yes, please do an origin pull and resolve any conflict

There is no conflict @shalomtaiwo

**Comment by shalomtaiwo** [comment]
Got it

**Pull request merged**
